<a href="https://colab.research.google.com/github/MuaazShoaib/tensorflow-developer-skills/blob/main/exercises/00_tensorflow_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Fundamentals Exercises


## Q1: Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [160]:
# Import the tensorflow
import tensorflow as tf

In [161]:
# Create a scalar
scalar = tf.constant(21)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [162]:
# Create a vector
vector = tf.constant([21, 22])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([21, 22], dtype=int32)>

In [163]:
# Create a matrix
matrix = tf.constant([[1, 2],
                      [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [164]:
# Create a tensor 
tensor = tf.constant([ [ [1, 2, 3],    [4, 5, 6],    [7, 8, 9] ],
                       [ [10, 11, 12], [13, 14, 15], [16, 17, 18] ],
                       [ [19, 20, 21], [22, 23, 24], [26, 27, 28] ] ])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [26, 27, 28]]], dtype=int32)>

## Q2: Find the shape, rank and size of the tensors you created in 1

In [165]:
# Let's find the shape of our scalar, vector, matrix and tensor
print(f"Shape of scalar is {scalar.shape}")
print(f"Shape of vector is {vector.shape}")
print(f"Shape of matrix is {matrix.shape}")
print(f"Shape of tensor is {tensor.shape}")

Shape of scalar is ()
Shape of vector is (2,)
Shape of matrix is (2, 2)
Shape of tensor is (3, 3, 3)


In [166]:
# Let's find the rank of our scalar, vector, matrix and tensor
print(f"Rank of scalar is {tf.rank(scalar)}")
print(f"Rank of vector is {tf.rank(vector)}")
print(f"Rank of matrix is {tf.rank(matrix)}")
print(f"Rank of tensor is {tf.rank(tensor)}")

Rank of scalar is 0
Rank of vector is 1
Rank of matrix is 2
Rank of tensor is 3


In [167]:
# Let's find the size of our scalar, vector, matrix and tensor
print(f"Size of scalar is {tf.size(scalar)}")
print(f"Size of vector is {tf.size(vector)}")
print(f"Size of matrix is {tf.size(matrix)}")
print(f"Size of tensor is {tf.size(tensor)}")

Size of scalar is 1
Size of vector is 2
Size of matrix is 4
Size of tensor is 27


## Q3: Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [168]:
# Create our first random tensor
random_tensor_1 = tf.random.uniform(shape=[5, 300])
random_tensor_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.85860956, 0.00195193, 0.40702534, ..., 0.30070937, 0.99951696,
        0.1596942 ],
       [0.7924259 , 0.7339566 , 0.61260605, ..., 0.02420127, 0.7978147 ,
        0.7850174 ],
       [0.58156824, 0.2869699 , 0.71779716, ..., 0.14286089, 0.12004876,
        0.28885448],
       [0.7858658 , 0.63497615, 0.7495785 , ..., 0.9402554 , 0.6601002 ,
        0.8622819 ],
       [0.47175527, 0.61394346, 0.27731383, ..., 0.6899054 , 0.8179256 ,
        0.07236385]], dtype=float32)>

In [169]:
# Create our second random tensor
random_tensor_2 = tf.random.uniform(shape=[5, 300])
random_tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.85946023, 0.8453622 , 0.5719652 , ..., 0.59839034, 0.41028082,
        0.84363973],
       [0.37625635, 0.5062573 , 0.81295514, ..., 0.44539583, 0.8500812 ,
        0.2728753 ],
       [0.41253507, 0.84780693, 0.6621851 , ..., 0.68239105, 0.916559  ,
        0.35940242],
       [0.2360121 , 0.20527196, 0.5881709 , ..., 0.73829997, 0.68141425,
        0.571658  ],
       [0.2283876 , 0.75911236, 0.9371692 , ..., 0.96036816, 0.3113693 ,
        0.04420877]], dtype=float32)>

## Q4: Multiply the two tensors you created in 3 using matrix multiplication.

In [170]:
# Multiply the two tensors using matrix multiplication
tf.linalg.matmul(random_tensor_1, tf.transpose(random_tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.58648 , 74.48924 , 73.00532 , 66.73194 , 72.56195 ],
       [79.623   , 78.61002 , 76.44096 , 73.44424 , 76.65093 ],
       [74.99753 , 76.5493  , 77.32937 , 72.629745, 77.56169 ],
       [78.32704 , 76.8571  , 77.27814 , 73.97169 , 80.37349 ],
       [77.16426 , 74.8389  , 73.46617 , 69.50926 , 76.55972 ]],
      dtype=float32)>

## Q5: Multiply the two tensors you created in 3 using dot product.

In [171]:
# Multiply the two tensors using dot product
tf.tensordot(random_tensor_1, tf.transpose(random_tensor_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.58648 , 74.48924 , 73.00532 , 66.73194 , 72.56195 ],
       [79.623   , 78.61002 , 76.44096 , 73.44424 , 76.65093 ],
       [74.99753 , 76.5493  , 77.32937 , 72.629745, 77.56169 ],
       [78.32704 , 76.8571  , 77.27814 , 73.97169 , 80.37349 ],
       [77.16426 , 74.8389  , 73.46617 , 69.50926 , 76.55972 ]],
      dtype=float32)>

## Q6: Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [172]:
# Create a random tensor
random_tensor_3 = tf.random.uniform(shape=[224, 224, 3])
random_tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.860716  , 0.02828157, 0.08573496],
        [0.3491    , 0.45013833, 0.01111233],
        [0.20068479, 0.20966566, 0.92417026],
        ...,
        [0.8897306 , 0.4671625 , 0.17027712],
        [0.7646797 , 0.13778996, 0.9500711 ],
        [0.42563987, 0.96943307, 0.9810568 ]],

       [[0.48822403, 0.19476902, 0.3190918 ],
        [0.4758637 , 0.02318692, 0.89308035],
        [0.26010394, 0.18963873, 0.14670444],
        ...,
        [0.67326593, 0.79181695, 0.76999414],
        [0.34706938, 0.85906005, 0.42769635],
        [0.2722262 , 0.96193695, 0.5646595 ]],

       [[0.5018407 , 0.74244213, 0.9963938 ],
        [0.41835368, 0.5455353 , 0.63503075],
        [0.49006426, 0.59326315, 0.66909933],
        ...,
        [0.8078475 , 0.01626539, 0.81756437],
        [0.05361569, 0.7703253 , 0.35478842],
        [0.8529792 , 0.7732649 , 0.44347155]],

       ...,

       [[0.12719023, 0.54127765, 0.19160223],
        [0.79

## Q7: Find the min and max values of the tensor you created in 6.

In [173]:
# Find the max and min values random_tensor_3
print(f"The max value is {tf.reduce_max(random_tensor_3)}")
print(f"The min value is {tf.reduce_min(random_tensor_3)}")

The max value is 0.9999967813491821
The min value is 3.5762786865234375e-07


## Q8: Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [174]:
# Create a tensor with random values of shape [1, 224, 224, 3]
random_tensor_4 = tf.random.normal(shape=[1, 224, 224, 3])
print(f"Before squeezing, the shape of our random_tensor_4  is {random_tensor_4.shape}")
print(f"After squeezing, the shape of our random_tensor_4  is {tf.squeeze(random_tensor_4).shape}")

Before squeezing, the shape of our random_tensor_4  is (1, 224, 224, 3)
After squeezing, the shape of our random_tensor_4  is (224, 224, 3)


## Q9: Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [175]:
# Create a random tensor
random_tensor_5 = tf.random.uniform(shape=[10], minval=1, maxval=10, dtype=tf.dtypes.int32)
random_tensor_5

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([7, 1, 6, 6, 5, 8, 3, 5, 6, 9], dtype=int32)>

In [176]:
# Find the index which has the maximum value.
print(f"The index of max value is {tf.math.argmax(random_tensor_5)}")

The index of max value is 9


## Q10: One-hot encode the tensor you created in 9.

In [177]:
# One-hot encode the tensor
tf.one_hot(random_tensor_5.numpy().tolist(), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>